game/gamemoguls/users/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField
from wtforms.validators import DataRequired, Length, Email, EqualTo, ValidationError
from gamemoguls.models import Users

class RegistrationForm(FlaskForm):
    """
    Form for user registration
    """
    username = StringField('Username', validators=[DataRequired(),Length(min=2,max=20)])
    email = StringField('Email', validators=[DataRequired(), Email(),Length(max=60)])
    password = PasswordField('Password', validators=[DataRequired(), Length(min=6,max=20)])
    confirm_password = PasswordField('Confirm Password', validators=[DataRequired(), EqualTo('password')])

class LoginForm(FlaskForm):
    """
    Form for user login
    """
    email = StringField('Email', validators=[DataRequired(), Email()])
    password = PasswordField('Password', validators=[DataRequired(), Length(min=6)])
    submit = SubmitField('Login')

class resetPasswordForm(FlaskForm):
    """
    Form for user reset password
    """
    email = StringField('Email', validators=[DataRequired(), Email()])
    submit = SubmitField('Reset Password')

    def validate (self, email):
        user = Users.query.filter_by(email=email.data).first()
        if user is None:
            raise ValidationError('If an account exists with that email, a reset link has been sent to your email')
        
class newPasswordForm(FlaskForm):
    password = PasswordField('Password', validators=[DataRequired(), Length(min=6,max=20)])
    confirm_password = PasswordField('Confirm Password', validators=[DataRequired(), EqualTo('password')])
    resetPassword = SubmitField('Reset Password')

game/gamemoguls/users/routes.py
from flask import blueprints, render_template, redirect, url_for, flash
from flask_login import login_user, logout_user, login_required, current_user, LoginManager
from werkzeug.security import generate_password_hash, check_password_hash
from gamemoguls.users.forms import RegistrationForm, LoginForm, resetPasswordForm, newPasswordForm
from gamemoguls import db, mail,login_manager
from gamemoguls.models import Users

users = blueprints.Blueprint('users', __name__)

@login_manager.user_loader
def load_user(user_id):
    """
    Load a user from the database using the user_id
    """
    return Users.query.get(int(user_id))

@users.route('/login', methods=['GET', 'POST'])
def login():
    """
    Log in a user
    """
    form = LoginForm()

    if form.validate_on_submit():
        # Check if the email and password match a user in the database
        user = Users.query.filter_by(email=form.email.data).first()
        if user and check_password_hash(user.password, form.password.data):
            login_user(user)
            return redirect(url_for('main.index'))

        flash('Invalid email or password', 'error')

    return render_template('users/login.html', form=form)

@users.route('/register' , methods=['GET', 'POST'])
def register():
    """
    Register a new user
    """
    form = RegistrationForm()

    if form.validate_on_submit():
        # Hash the password before storing it in the database
        hashed_password = generate_password_hash(form.password.data, method='scrypt')

        # Create a new User object with the form data and add it to the database
        new_user = Users(username=form.username.data, email=form.email.data, password=hashed_password)
        db.session.add(new_user)
        db.session.commit()

        flash('Your account has been created! You are now able to log in.', 'success')
        return redirect(url_for('users.login'))

    return render_template('users/register.html', title='Register', form=form)

@users.route('/profile')
@login_required
def profile():

    return render_template('users/profile.html')

@users.route('/logout')
@login_required
def logout():
    """
    Log out the current user
    """
    logout_user()
    return redirect(url_for('main.index'))

@users.route('/resetPassword', methods=['GET', 'POST'])
def reset_request(token):
    if current_user.is_authenticated:
        return redirect(url_for('index'))
    form = resetPasswordForm()
    if form.validate_on_submit():
        user = Users.query.filter_by(email=form.email.data).first()
        if user is None:
            flash('If an account exists with that email, a reset link has been sent to your email', 'info')
        else:
            token = Users.get_reset_token(user)
            mail.send_message('Password Reset Request',
                              
            )
            flash('If an account exists with that email, a reset link has been sent to your email', 'info')
        
    return render_template('users/resetPassword.html', form=form)

@users.route('/resetPassword/<token>', methods=['GET', 'POST'])
def resetpassword(token):
    if current_user.is_authenticated:
        return redirect(url_for('index'))
    user = Users.verify_reset_token(token)
    if user is None:
        flash('That is an invalid or expired token', 'warning')
        return redirect(url_for('users.reset_request'))
    form = newPasswordForm()

    return render_template('users/newPassword.html', form=form)

game/gamemoguls/templates/users/login.html
{% extends "main.html" %}

{% block content %}
<div class="form-box">
<h1>Login</h1>
    <form method="POST">
        {{ form.csrf_token }}
        <div class="form-group">
            {{ form.email.label(class_="form-label") }}
            {{ form.email(class_="form-control") }}
        </div>
        <div class="form-group">
            {{ form.password.label(class_="form-label") }}
            {{ form.password(class_="form-control") }}
        </div>
        {{ form.submit(class_="btn btn-primary") }}
    </form>
    <div class="mt-3">
        <a href="{{ url_for('users.register') }}">Don't have an account click here to register</a>
    </div>
</div>
{% endblock %}

game/gamemoguls/templates/users/profile.html
{% extends "main.html" %}
{% block content %}
<h1>Profile</h1>
<h2>Username: {{ current_user.username }}</h2>

{% endblock %}

game/gamemoguls/templates/users/register.html
{% extends "main.html" %}

{% block content %}
<div class="form-box">
  <h1>Register</h1>
  <form method="POST">
    {{ form.csrf_token }}
    <div class="form-group">
      {{ form.username.label(class_="form-label") }}
      {{ form.username(class_="form-control") }}
    </div>
    <div class="form-group">
      {{ form.email.label(class_="form-label") }}
      {{ form.email(class_="form-control") }}
    </div>
    <div class="form-group">
      {{ form.password.label(class_="form-label") }}
      {{ form.password(class_="form-control") }}
    </div>
    <div class="form-group">
      {{ form.confirm_password.label(class_="form-label") }}
      {{ form.confirm_password(class_="form-control") }}
    </div>
    <button type="submit" class="btn btn-primary">Register</button>
  </form>
</div>
{% endblock %}

game/gamemoguls/templates/users/resetPassword.html
{% extends "main.html" %}

{% block content %}
<h1>Reset Password</h1>
<form method="POST">
  {{ form.csrf_token }}
  <div class="form-group">
    {{ form.email.label(class_="form-label") }}
    {{ form.email(class_="form-control") }}
  </div>
  <button type="submit" class="btn btn-primary">Reset Password</button>
</form>
{% endblock %}